version: '3.3'

services:
  mysql:
    image: mysql:5.7
    container_name: crudpixmysql
    environment:
      MYSQL_ROOT_PASSWORD: 12qwaszx
      MYSQL_DATABASE: crudpix
      MYSQL_USER: admpix
      MYSQL_PASSWORD: 12qwaszx
    ports:
      - "3306:3306"
    volumes:
      - ./dados_mysql:/var/lib/mysql
